#!/bin/bash

source $MODULESHOME/init/bash
module reset

unset CTEST_BUILD_NAME
unset CC
unset CXX
unset FC
unset YAKL_ARCH
unset YAKL_VERBOSE
unset YAKL_VERBOSE_FILE
unset YAKL_DEBUG
unset YAKL_HAVE_MPI
unset YAKL_ENABLE_STREAMS
unset YAKL_AUTO_PROFILE
unset YAKL_AUTO_FENCE
unset YAKL_B4B
unset YAKL_MANAGED_MEMORY
unset YAKL_MEMORY_DEBUG
unset YAKL_TARGET_SUFFIX
unset YAKL_F90_FLAGS
unset YAKL_CXX_FLAGS
unset YAKL_OPENMP_FLAGS
unset YAKL_CUDA_FLAGS
unset YAKL_HIP_FLAGS
unset YAKL_SYCL_FLAGS
unset CTEST_GCOV
unset CTEST_VALGRIND
unset GATOR_DISABLE
unset GATOR_INITIAL_MB
unset GATOR_GROW_MB
unset GATOR_BLOCK_BYTES
unset CFLAGS
unset CXXFLAGS
unset FFLAGS
unset FCFLAGS
unset CUDAFLAGS

