
#include "YAKL.h"
#define KOKKOS_IMPL_PUBLIC_INCLUDE
#include <impl/Kokkos_SharedAlloc_timpl.hpp>
#undef KOKKOS_IMPL_PUBLIC_INCLUDE

#ifdef KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_SERIAL
KOKKOS_IMPL_SHARED_ALLOCATION_RECORD_EXPLICIT_INSTANTIATION(yakl::PoolSpace);
#else
KOKKOS_IMPL_HOST_INACCESSIBLE_SHARED_ALLOCATION_RECORD_EXPLICIT_INSTANTIATION(yakl::PoolSpace);
#endif

